{"name": "计算加法中字符串和数字相加情况", "status": "passed", "attachments": [{"name": "log", "source": "8180ea89-20dd-4f49-8f50-9da68478b84e-attachment.txt", "type": "text/plain"}], "start": 1626020561596, "stop": 1626020561596, "uuid": "d09baa60-47d8-49d0-a746-7707509b8bff", "historyId": "814c38d00bd71c9bd4772b834b90545e", "testCaseId": "0207c489f6e2db85411d959418473b71", "fullName": "test_calcul_yml.Test_calculate#test_add_error", "labels": [{"name": "feature", "value": "计算器模块"}, {"name": "story", "value": "相加失败，预期会抛异常"}, {"name": "suite", "value": "test_calcul_yml"}, {"name": "subSuite", "value": "Test_calculate"}, {"name": "host", "value": "PC-20200730PITZ"}, {"name": "thread", "value": "23080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calcul_yml"}]}